# redis-server.yml
version: '3.7'
services:
  django:
    build: .
    command: 'python3 manage.py runserver 0.0.0.0:${PORT}'
    container_name: ${CONTAINER_NAME}
    hostname: root
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    environment:
      TZ: 'Asia/Seoul'