# redis-server.yml
version: '3.7'
services:
  django:
    build: .
    command: 'python3 manage.py runserver 0.0.0.0:${PORT}'
    container_name: ${CONTAINER_NAME}
    hostname: root
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    environment:
      TZ: 'Asia/Seoul'
    depends_on:
      - "db"
  db:
    
    image: 'mariadb:latest'
    container_name: 'db'
    ports:
      - '3306:3306'
    # volumes:
    #   - /docker_projects/mariadb__1/etc:/etc/mysql
    #   - /docker_projects/mariadb__1/run/mysqld:/run/mysqld
    #   - /docker_projects/mariadb__1/mysql:/var/lib/mysql
    environment:
      MARIADB_USER: '${DB_HOST}'
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_DATABASE: 'media'
      TZ: 'Asia/Seoul'
    restart: unless-stopped
  redis:
    image: redis:latest
    command: 'redis-server --port 6379 --appendonly yes --requirepass ${DB_PASSWORD}'
    container_name: redis
    hostname: root
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
    restart: unless-stopped
    environment:
      TZ: 'Asia/Seoul'
