# redis-server.yml
version: '3.7'
services:
  django:
    build: .
    command: 'sh command.sh ${PORT}'
    # command : "tail -f /dev/null"
    container_name: ${CONTAINER_NAME}
    hostname: root
    # volumes:
    #   - /docker_projects/nginx__1/data/site_projects/media:/usr/src/app/media
    #   - .:/usr/src/app
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
