# Generated by Django 4.0.5 on 2022-07-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file_path', models.CharField(max_length=256, verbose_name='파일경로')),
                ('file_url', models.CharField(max_length=256, verbose_name='파일URL')),
                ('origin', models.CharField(default='default', max_length=100, verbose_name='출처')),
            ],
        ),
        migrations.CreateModel(
            name='MyFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='파일이름')),
                ('size', models.IntegerField(verbose_name='파일사이즈')),
                ('key', models.CharField(max_length=128, verbose_name='파일 키')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.myfiles')),
            ],
        ),
    ]
