# Generated by Django 4.0.5 on 2022-07-15 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfiles',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 15, 5, 54, 50, 435055, tzinfo=utc), verbose_name='등록날짜'),
            preserve_default=False,
        ),
    ]
