# Generated by Django 4.0.5 on 2022-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_myfiles_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='인증 완료됨'),
        ),
    ]
